# Generated by Django 5.1.4 on 2024-12-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ARModel',
            fields=[
                ('modelId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('qrurl', models.URLField()),
                ('url', models.URLField()),
            ],
        ),
    ]
